version: '3.9'
services:
  mysql:
    container_name: "MySQL"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: override
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: app
      MYSQL_USER: server
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - "./server/db/:/var/lib/mysql"
